### ISSUE TITLE
Improving Overall UI of the App ,

### ISSUE THREAD

**Issue by ROUNAK-K-JHA-2002** [m0hit-kumar/Bring-The-Menu#13]
WIll improve overall UI of the App  along with options like darkmode and lightmode , etc

**Comment by ROUNAK-K-JHA-2002** [comment]
please Assign this issue to me under GSSoc'23 Contributor Program

**Comment by m0hit-kumar** [comment]
> WIll improve overall UI of the App along with options like darkmode and lightmode , etc

kindly provide the Figma link for the updated UI and refer to the #10 convo

**Comment by ROUNAK-K-JHA-2002** [comment]
https://www.figma.com/file/1HMG3G53Yg1c6naUDFHOGG/Restaurant-App-(Community)?type=design&node-id=0-1&t=0Khceul1ypVbsiT9-0
I will take inspiration from here.
