### ISSUE TITLE
Integrating Google SignIn instead of Email password Sign in for better User Experience

### ISSUE THREAD

**Issue by ROUNAK-K-JHA-2002** [m0hit-kumar/Bring-The-Menu#15]

**Comment by ROUNAK-K-JHA-2002** [comment]
please Assign this issue to me under GSSoC'23 Contributor Program

**Comment by m0hit-kumar** [comment]
> please Assign this issue to me under GSSoC'23 Contributor Program

Our app goal is assigned with mobile authentication and further we are planning to connect it through UPI so we have mobile auth
