### ISSUE TITLE
Dark and Light Mode[GSSoC'23]

### ISSUE THREAD

**Issue by AnubhaSharma2709** [m0hit-kumar/Bring-The-Menu#26]
Dark and Light Mode Option should be given.
Please assign this to me 
Under GSSoC'23

**Comment by Saksham0205** [comment]
please assign me this issue I have knowledge of this functionality.

**Comment by avirupnandi1** [comment]
Please assign me this Issue, I have done it in my projects, I can do this

**Comment by m0hit-kumar** [comment]
kindly send me the updated UI image to look at so I can better decide whom to assign and the conversation is moving to #10
