### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [m0hit-kumar/Bring-The-Menu#27]
I want to add readme badges .Please assign this issue to me 
![badges](https://github.com/m0hit-kumar/Bring-The-Menu/assets/104543751/5149744c-cb07-4cb8-b712-859d85bfa74a)

**Comment by m0hit-kumar** [comment]
conversation moved to #12

**Comment by S-ishita** [comment]
So  can't I work on this @m0hit-kumar ???

**Comment by m0hit-kumar** [comment]
> So can't I work on this @m0hit-kumar ???

i said go ahead means start working, i just moved the conversation. maintaining so many issues is not possible so I am clubbing similar issues into one

**Comment by S-ishita** [comment]
Okay please add me as assignee
