### ISSUE TITLE
Obscure password input while admin login [GSSoC'23]

### ISSUE THREAD

**Issue by TikuGaelle** [m0hit-kumar/Bring-The-Menu#29]
The password input is not obscured, hence not secured. I can also add the option to make password visible, if required by the user.
Please assign this issue to me.

**Comment by m0hit-kumar** [comment]
> The password input is not obscured, hence not secured. I can also add the option to make password visible, if required by the user. Please assign this issue to me.

you can go ahead

**Comment by ayushgit2003** [comment]
Regarding the obscure password input during admin login issue, I propose implementing password masking, a visibility toggle, and a confirmation prompt to enhance security and user experience. Please assign this issue to me under GSSoC'23.

**Comment by TikuGaelle** [comment]
> > The password input is not obscured, hence not secured. I can also add the option to make password visible, if required by the user. Please assign this issue to me.
> 
> you can go ahead

Okay, thanks.

**Comment by shubham725809** [comment]
I am an expert in providing authentication,so please assign me this task,i will definitely resolve this issue
