### ISSUE TITLE
Readme.md file needs improvement

### ISSUE THREAD

**Issue by DiyaVj** [m0hit-kumar/Bring-The-Menu#38]
We have an important task at hand: improving the readme.md file for our project. A well-crafted readme.md file is crucial for providing a clear understanding of our project's purpose, installation process, and usage instructions.

**Comment by Pratik-11** [comment]
You can assign this issue to me . ill be working on it. Will initiate the readme add components, sections like welcome ,contributors etc, then people can contribute to different sections
