### ISSUE TITLE
[GSSoC'23] Improve the project image dashboard in the Readme file 

### ISSUE THREAD

**Issue by anandanmukh** [m0hit-kumar/Bring-The-Menu#55]
**Is your feature request related to a problem? Please describe.**
The app screenshots don't look that inspiring. We need to make it more presentable. I just want to make it seem more appealing for anyone visiting the project.

**Describe the solution you'd like**
- I would put the images(screenshots) in the Bring-The-Menu/graphics folder and add a frame to it, and finally add it to a poster. I can also do it with a phone, so it would showcase different devices.
- I would choose the colour of the background in accordance with the design theme

**Additional context**
@m0hit-kumar    Please assign this to me under the GSSoC'23. 
### I have added some examples of how this project could look like (from my own repo)
![flutter_projects_1](https://github.com/avinashkranjan/Friday/assets/67072228/5187cd02-6593-44b3-9ecf-f7b9da5c7d5a)
## [Friday](https://github.com/avinashkranjan/Friday)
![friday_application_preview](https://github.com/codervivek5/VigyBag/assets/67072228/bf505ba0-1b74-40bb-98ca-3ec00865cf95)

**Comment by m0hit-kumar** [comment]
issue has been clubbed under single issue(#84 ) for management purposes you can still keep work on it and do the PR
