### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by soham-1902** [m0hit-kumar/Bring-The-Menu#63]
**Describe the bug**
The Restaurant Name and Location Textfields have the same controller. In other words when you type text in Restaurant Name field, it is also reflected in Location field which is not desirable.

**To Reproduce**
Go to Complete Profile page for Admin

**Expected behavior**
Text in Restaurant Name field should not be reflected in Location field.

**Screenshots**
Video:
https://github.com/m0hit-kumar/Bring-The-Menu/assets/120256780/717e0186-4bac-46b7-9c58-6d986d120171

Screenshot:
![WhatsApp Image 2023-06-03 at 12 20 13 AM](https://github.com/m0hit-kumar/Bring-The-Menu/assets/120256780/5888e19a-0991-4a53-a241-b2c8224c0ec9)

**Smartphone:**
 - Device: Samsung M31s
 - OS: Android

**Comment by soham-1902** [comment]
Kindly assign me this issue under GSSoC 2023.

**Comment by ViAsmit** [comment]
@soham-1902 Its already fixed in another PR.
