### ISSUE TITLE
Fix Markdown in Readme

### ISSUE THREAD

**Issue by Sriparno08** [m0hit-kumar/Bring-The-Menu#69]
**Describe the bug**

In the last line, the markdown needs to be fixed.

**Screenshots**

![Screenshot 2023-06-06 130241](https://github.com/m0hit-kumar/Bring-The-Menu/assets/89148144/28a58f0f-3b66-402e-ac5a-fd792bb9daf5)

**To Reproduce**

1. Go to README.md
2. Scroll down to 'Contribute to Bring_The_Menu'

**Expected behavior**

The link to the CONTRIBUTING.md file should be put inside the first brackets.

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser Chrome
 - Version 113
 
**Additional context**

I would like to contribute as part of GSSoC'23.

**Comment by m0hit-kumar** [comment]
issue has been clubbed under single issue(#84 ) for management purposes you can still keep work on it and do the PR
