### ISSUE TITLE
unnecessary OTP page

### ISSUE THREAD

**Issue by helloamj** [m0hit-kumar/Bring-The-Menu#8]
# Issue
Verification used is not OTP Verification its Email link verification

**Comment by helloamj** [comment]
@m0hit-kumar Sir I just used my mail to verify can i have the opportunity to solve this issue please it assign to me

**Comment by Harsh1350** [comment]
I see that verification used is not OTP verification it is  email link verification  I want to solve this issue please assign me this @m0hit-kumar 
I am a GSSOC'23 contributor

**Comment by m0hit-kumar** [comment]
> # Issue
> Verification used is not OTP Verification its Email link verification

we have an OTP page that has to be implemented, but the backend is not been implemented yet, if you are up to do it let me know. Firebase is to be used for OTP [ same goes for you guys @Harsh1350 @yash-jain-1 ]

**Comment by helloamj** [comment]
Ya i wanna work on it @m0hit-kumar

**Comment by m0hit-kumar** [comment]
> Ya i wanna work on it @m0hit-kumar could you plz assign it to me

go ahead
