### ISSUE TITLE
Form page issue

### ISSUE THREAD

**Issue by rohitranjan753** [m0hit-kumar/Bring-The-Menu#82]
**Describe the bug**
1. Restaurant Name field contain text capitalization.
2. Phone number field should take only number and keyboard type should be number only.
3. Website feild should take proper website format (www.something.com)
4. Location feild should take actual google location

**To Reproduce**
1. Go to form page
2. Click on either Restaurant Name or Phone number or Website or Location feild.
4. We can see the reported issue as mentioned above.

**Expected behavior**
Number keyboard type for phone number, text capitalization for restaurant name, proper format of website input, actual geo location.

**Screenshots**
![WhatsApp Image 2023-06-21 at 9 23 24 PM](https://github.com/m0hit-kumar/Bring-The-Menu/assets/57181495/fb8f8fe6-bd4a-4e15-b745-551fb62dd22f)

![WhatsApp Image 2023-06-21 at 9 24 04 PM](https://github.com/m0hit-kumar/Bring-The-Menu/assets/57181495/cb126eb9-19c5-4863-ad70-2968c60819b2)

![WhatsApp Image 2023-06-21 at 9 24 35 PM](https://github.com/m0hit-kumar/Bring-The-Menu/assets/57181495/e67db7aa-4491-42d1-a65c-a9692391edc3)

![WhatsApp Image 2023-06-21 at 9 25 36 PM](https://github.com/m0hit-kumar/Bring-The-Menu/assets/57181495/ff44733d-a050-4285-b535-41387b948b8c)

**Smartphone (please complete the following information):**
   - Device: Realme X2
 - OS: Android 11

#gssoc23 #bug #bugreport

**Comment by theshubh007** [comment]
Hey mohit,
I can solve this issue,
Assign this to me under gssoc'23.

**Comment by m0hit-kumar** [comment]
someone is already working on it @rohitranjan753

**Comment by m0hit-kumar** [comment]
someone is already working on it @rohitranjan753
