### ISSUE TITLE
adding tech stack badges and shields for better understanding of technologies used

### ISSUE THREAD

**Issue by barkhaaroraa** [m0hit-kumar/Bring-The-Menu#83]
**Is your feature request related to a problem? Please describe.**
adding tech stacks used in the readme.md file

**Describe the solution you'd like**
it'd make readme more attractive 

**Describe alternatives you've considered**

**Additional context**ns or features you've considered.
<img width="654" alt="image" src="https://github.com/m0hit-kumar/Bring-The-Menu/assets/115429121/52a5b008-a1a2-49da-9520-5da4938c122d">
picture for reference

**Comment by m0hit-kumar2** [comment]
you can add go ahead

**Comment by m0hit-kumar** [comment]
issue has been clubbed under single issue(#84 ) for management purposes you can still keep work on it and do the PR
