### ISSUE TITLE
Widget Overflow in Admin dashboard

### ISSUE THREAD

**Issue by theshubh007** [m0hit-kumar/Bring-The-Menu#85]
**Describe the bug**
In the admin dashboard there is order card which overflows right side

**To Reproduce**
1. Go to Admin dashboard
2. See error

**Expected behavior**
In the admin dashboard there is order card you'll see above "recent order" Title ,
whose width overflows right side

**Screenshots**
![WhatsApp Image 2023-06-25 at 13 29 51](https://github.com/m0hit-kumar/Bring-The-Menu/assets/100220928/84b812a6-1fdf-4c76-9286-4548cb5762ee)

**Smartphone (please complete the following information):**
 - Device: Realme7
 - OS: Android 11

**Comment by theshubh007** [comment]
I can fix this issue under GSSoc 23.

**Comment by m0hit-kumar** [comment]
go ahead
