### ISSUE TITLE
adding the sigin and signup with firebase

### ISSUE THREAD

**Issue by LegendSumeet** [m0hit-kumar/Bring-The-Menu#9]
can you assign this to me, I want to work on this under GSSoC'23

**Comment by mridul45** [comment]
Greetings , I went through the project list and found that my skills will be best suited for this project . As a GSSOC 23 contributor kindly allow me to contribute to the project.

**Comment by ayush-raj26** [comment]
Hello!
Can you please assign me this issue I would love to work on this.

**Comment by Harsh1350** [comment]
Hey can you please assign me this I want to work on this issue

**Comment by m0hit-kumar** [comment]
it already been addressed in #8 [@Harsh1350 , @ayush-raj26 , @mridul45 , @LegendSumeet ]
